bamboo-specs: Add basic topotest for LXC verification
Signed-off-by: Martin Winter <mwinter@opensourcerouting.org>

diff --git a/bamboo-specs/bamboo.yml b/bamboo-specs/bamboo.yml
--- a/bamboo-specs/bamboo.yml
+++ b/bamboo-specs/bamboo.yml
@@ -165,7 +165,8 @@ Build_Ubuntu1804_amd64:
           #
           # Install new image
           - lxc-stop -n ${lxcName} ?| true
-          - lxc-destroy -n ${lxcName} ?| true
+          - sleep 15
+          - lxc-destroy -f -n ${lxcName} ?| true
           - lxc-create -n ${lxcName} -t local -- --metadata meta.tar.xz --fstree rootfs.tar.xz
           #
           # Copy authorized_keys from LXC host root user to LXC image, root & ci users
@@ -190,11 +191,15 @@ Build_Ubuntu1804_amd64:
           - echo "ff02::2     ip6-allrouters" >> /var/lib/lxc/${lxcName}/rootfs/etc/hostname
           - echo "${lxcName}" > /var/lib/lxc/${lxcName}/rootfs/etc/hostname
           #
+          - sync
+          - sleep 10
+          #
           # Install OpenSSH
           - lxc-start ${lxcName}
           # Wait for network
           - attempts=50
           - reachable=0
+          - set +e
           - while [ $reachable -eq 0 ];
           - do
           -   sleep 1
@@ -215,6 +220,7 @@ Build_Ubuntu1804_amd64:
           -     fi
           -   fi    
           - done
+          - set -e
           # Got IP and can ping server - wait another 15 sec
           - sleep 15
           # Now install OpenSSH-Server
@@ -222,6 +228,7 @@ Build_Ubuntu1804_amd64:
           # And power it off. Finish building the container
           - lxc-attach ${lxcName} -- poweroff
           - sleep 10
+          - lxc-stop ${lxcName}
           #
           - echo "update=DONE" > ${bamboo_build_working_directory}/status.txt
 
@@ -261,6 +268,9 @@ Build_Ubuntu1804_amd64:
           - cd test
           - wget -q https://ci1.netdef.org/browse/FRR-FRR/latestSuccessful/artifact/shared/SourceCode/frr-source.tar.gz
           #
+          - sync
+          - sleep 10
+          #
           # Start a clone of the new container
           - LXCname=${lxcTemplate}_${lxcRelease}_${lxcArch}
           - LXCvm=TEST_${LXCname}
@@ -268,6 +278,7 @@ Build_Ubuntu1804_amd64:
           # Check and Wait for host to be pingable
           - attempts=50
           - reachable=0
+          - set +e
           - while [ $reachable -eq 0 ];
           - do
           -   sleep 1
@@ -306,6 +317,7 @@ Build_Ubuntu1804_amd64:
           -     sleep 10
           -   fi    
           - done
+          - set -e
           - host="$(echo -e "${host}" | tr -d '[:space:]')"
           - echo "LXChost=${host}" > ${bamboo_build_working_directory}/jobconfig.ini
           - chmod 755 ${bamboo_build_working_directory}/jobconfig.ini
@@ -429,6 +441,8 @@ Topotest_Ubuntu1804_amd64:
           -     set -x
           - fi
           #
+          - set -e
+          #
           ##### EDIT HERE #####
           - lxcReleaseName=bionic
           - lxcRelease=ubuntu1804
@@ -480,7 +494,7 @@ Topotest_Ubuntu1804_amd64:
           - distrobuilder build-dir ${lxcYAML} ${lxcTemplate} -o image.release=${lxcReleaseName} -o image.architecture=${lxcArch}
           #
           # Add README.Sourceversion.txt
-          - cp ${bamboo_build_working_directory}/README.SourceVersion.txt ${lxcTemplate}/etc/README.SourceVersion.txt
+          - cp ${bamboo_build_working_directory}/README.SourceVersion.txt ${lxcTemplate}/etc/README.SourceVersion.temp
           #
           # Pack up image
           - export XZ_DEFAULTS="-T 0"
@@ -489,7 +503,8 @@ Topotest_Ubuntu1804_amd64:
           #
           # Install new image
           - lxc-stop -n ${lxcName} ?| true
-          - lxc-destroy -n ${lxcName} ?| true
+          - sleep 15
+          - lxc-destroy -f -n ${lxcName} ?| true
           - lxc-create -n ${lxcName} -t local -- --metadata meta.tar.xz --fstree rootfs.tar.xz
           #
           # Copy authorized_keys from LXC host root user to LXC image, root & ci users
@@ -514,11 +529,15 @@ Topotest_Ubuntu1804_amd64:
           - echo "ff02::2     ip6-allrouters" >> /var/lib/lxc/${lxcName}/rootfs/etc/hostname
           - echo "${lxcName}" > /var/lib/lxc/${lxcName}/rootfs/etc/hostname
           #
+          - sync
+          - sleep 10
+          #
           # Install OpenSSH
           - lxc-start ${lxcName}
           # Wait for network
           - attempts=50
           - reachable=0
+          - set +e
           - while [ $reachable -eq 0 ];
           - do
           -   sleep 1
@@ -539,6 +558,7 @@ Topotest_Ubuntu1804_amd64:
           -     fi
           -   fi    
           - done
+          - set -e
           # Got IP and can ping server - wait another 15 sec
           - sleep 15
           # Now install OpenSSH-Server
@@ -546,6 +566,7 @@ Topotest_Ubuntu1804_amd64:
           # And power it off. Finish building the container
           - lxc-attach ${lxcName} -- poweroff
           - sleep 10
+          - lxc-stop ${lxcName} ?| true
           #
           - echo "update=DONE" > ${bamboo_build_working_directory}/status.txt
 
@@ -562,6 +583,8 @@ Topotest_Ubuntu1804_amd64:
           - if [ "$bamboo_ci_script_verbose" != "" ]; then
           -     set -x
           - fi
+          #
+          - set -e
           #
           ####################################
           # Start LXC Container
@@ -585,6 +608,9 @@ Topotest_Ubuntu1804_amd64:
           - mv ${bamboo_build_working_directory}/frr-source.tar.gz ${bamboo_build_working_directory}/test/
           - mv ${bamboo_build_working_directory}/*.deb ${bamboo_build_working_directory}/test/
           #
+          - sync
+          - sleep 10
+          #
           # Start a clone of the new container
           - LXCname=${lxcTemplate}_${lxcRelease}_${lxcArch}
           - LXCvm=TEST_${LXCname}
@@ -592,6 +618,7 @@ Topotest_Ubuntu1804_amd64:
           # Check and Wait for host to be pingable
           - attempts=50
           - reachable=0
+          - set +e
           - while [ $reachable -eq 0 ];
           - do
           -   sleep 1
@@ -630,6 +657,7 @@ Topotest_Ubuntu1804_amd64:
           -     sleep 10
           -   fi    
           - done
+          - set -e
           - host="$(echo -e "${host}" | tr -d '[:space:]')"
           - echo "LXChost=${host}" > ${bamboo_build_working_directory}/jobconfig.ini
           - chmod 755 ${bamboo_build_working_directory}/jobconfig.ini
@@ -649,6 +677,8 @@ Topotest_Ubuntu1804_amd64:
           -     set -x
           - fi
           #
+          - set -e
+          #
           - if [ "${bamboo.LXC.update}" = "SKIP" ]; then
           -   echo "Skipped. LXC Image was not rebuilt"
           -   exit 0
@@ -666,52 +696,74 @@ Topotest_Ubuntu1804_amd64:
           - LXCname=${lxcTemplate}_${lxcRelease}_${lxcArch}
           - LXCvm=TEST_${LXCname}
           #
-          - ssh root@${LXChost} "tar xzf share/frr-source.tar.gz"
+          - ssh -t root@${LXChost} 'curl -s https://deb.frrouting.org/frr/keys.asc | sudo DEBIAN_FRONTEND=noninteractive apt-key add -'
+          - ssh root@${LXChost} 'echo deb https://deb.frrouting.org/frr $(lsb_release -s -c) frr-stable | tee -a /etc/apt/sources.list.d/frr.list'
+          - ssh root@${LXChost} 'DEBIAN_FRONTEND=noninteractive apt update'
+          - ssh root@${LXChost} 'DEBIAN_FRONTEND=noninteractive apt install -y libyang-dev'
+          #
+          # Install topotest scripts and FRR
+          - ssh root@${LXChost} 'tar xzf share/frr-source.tar.gz'
+          - ssh root@${LXChost} 'DEBIAN_FRONTEND=noninteractive dpkg -i share/frr_*.deb'
+          - ssh root@${LXChost} 'DEBIAN_FRONTEND=noninteractive dpkg -i share/frr-python*.deb'
+          - ssh root@${LXChost} 'systemctl disable frr'
+          - ssh root@${LXChost} 'systemctl stop frr'
+          #
+          # Start OVSswitch
+          - ssh root@${LXChost} 'frr-source/tests/topotests/docker/inner/openvswitch.sh'
+          #
+          # Run limited topotests
+          - ssh root@${LXChost} 'cd frr-source/tests/topotests/all-protocol-startup/; ./test_all_protocol_startup.py'
+          - if [ $? -eq 0 ]; then
+          -    echo "Topotest passed. All good"
+          - else
+          -    ">&2 echo 'Topotest all_protocol_startup failed. LXC container failed'"
+          -    exit 1
+          - fi
 
-    # - script:
-    #     interpreter: shell
-    #     scripts:
-    #       - "#!/usr/bin/env bash"
-    #       # For Debugging define the ci_script_verbose variable in config to some value
-    #       - if [ "$bamboo_ci_script_verbose" != "" ]; then
-    #       -     set -x
-    #       - fi
-    #       #
-    #       - if [ "${bamboo.LXC.update}" = "SKIP" ]; then
-    #       -   echo "Skipped. LXC Image was not rebuilt"
-    #       -   exit 0
-    #       - elif [ "${bamboo.LXC.boot}" != "DONE" ]; then
-    #       -   echo "Skipped. LXC Image was not started (start failure)"
-    #       -   exit 0
-    #       - fi
-    #       #
-    #       - . ${bamboo_build_working_directory}/README.SourceVersion.txt
-    #       - LXCname=${lxcTemplate}_${lxcRelease}_${lxcArch}
-    #       # Rename README.SourceVersion.temp to README.SourceVersion.txt to mark working container
-    #       - mv /var/lib/lxc/${LXCname}/rootfs/etc/README.SourceVersion.temp /var/lib/lxc/${LXCname}/rootfs/etc/README.SourceVersion.txt
+    - script:
+        interpreter: shell
+        scripts:
+          - "#!/usr/bin/env bash"
+          # For Debugging define the ci_script_verbose variable in config to some value
+          - if [ "$bamboo_ci_script_verbose" != "" ]; then
+          -     set -x
+          - fi
+          #
+          - if [ "${bamboo.LXC.update}" = "SKIP" ]; then
+          -   echo "Skipped. LXC Image was not rebuilt"
+          -   exit 0
+          - elif [ "${bamboo.LXC.boot}" != "DONE" ]; then
+          -   echo "Skipped. LXC Image was not started (start failure)"
+          -   exit 0
+          - fi
+          #
+          - . ${bamboo_build_working_directory}/README.SourceVersion.txt
+          - LXCname=${lxcTemplate}_${lxcRelease}_${lxcArch}
+          # Rename README.SourceVersion.temp to README.SourceVersion.txt to mark working container
+          - mv /var/lib/lxc/${LXCname}/rootfs/etc/README.SourceVersion.temp /var/lib/lxc/${LXCname}/rootfs/etc/README.SourceVersion.txt
 
-  # final-tasks:
-  #    - script:
-  #       interpreter: shell
-  #       scripts:
-  #         - "#!/usr/bin/env bash"
-  #         # For Debugging define the ci_script_verbose variable in config to some value
-  #         - if [ "$bamboo_ci_script_verbose" != "" ]; then
-  #         -     set -x
-  #         - fi
-  #         #
-  #         ####################################
-  #         # LXC Container Stopping
-  #         ####################################
-  #         #
-  #         ##- if [ "${bamboo.LXC.update}" = "SKIP" ]; then
-  #         ##-   echo "Skipped. LXC Image was not rebuilt"
-  #         ##-   exit 0
-  #         ##- elif [ "${bamboo.LXC.update}" != "DONE" ]; then
-  #         ##-   echo "Skipped. LXC Image build failed"
-  #         ##-   exit 0
-  #         ##- fi
-  #         #
-  #         - . ${bamboo_build_working_directory}/README.SourceVersion.txt
-  #         - LXCvm=TEST_${lxcTemplate}_${lxcRelease}_${lxcArch}
-  #         - lxc-stop -n ${LXCvm}
+  final-tasks:
+     - script:
+        interpreter: shell
+        scripts:
+          - "#!/usr/bin/env bash"
+          # For Debugging define the ci_script_verbose variable in config to some value
+          - if [ "$bamboo_ci_script_verbose" != "" ]; then
+          -     set -x
+          - fi
+          #
+          ####################################
+          # LXC Container Stopping
+          ####################################
+          #
+          - if [ "${bamboo.LXC.update}" = "SKIP" ]; then
+          -   echo "Skipped. LXC Image was not rebuilt"
+          -   exit 0
+          - elif [ "${bamboo.LXC.update}" != "DONE" ]; then
+          -   echo "Skipped. LXC Image build failed"
+          -   exit 0
+          - fi
+          #
+          - . ${bamboo_build_working_directory}/README.SourceVersion.txt
+          - LXCvm=TEST_${lxcTemplate}_${lxcRelease}_${lxcArch}
+          - lxc-stop -n ${LXCvm}
