bamboo-specs: Install SSH on topotest container
Signed-off-by: Martin Winter <mwinter@opensourcerouting.org>

diff --git a/bamboo-specs/bamboo.yml b/bamboo-specs/bamboo.yml
--- a/bamboo-specs/bamboo.yml
+++ b/bamboo-specs/bamboo.yml
@@ -189,7 +189,7 @@ Build_Ubuntu1804_amd64:
           - echo "ff02::2     ip6-allrouters" >> /var/lib/lxc/${lxcName}/rootfs/etc/hostname
           - echo "${lxcName}" > /var/lib/lxc/${lxcName}/rootfs/etc/hostname
           #
-          # Create new SSH Host keys
+          # Install OpenSSH
           - lxc-start ${lxcName}
           # Wait for network
           - attempts=50
@@ -505,9 +505,36 @@ Topotest_Ubuntu1804_amd64:
           - echo "ff02::2     ip6-allrouters" >> /var/lib/lxc/${lxcName}/rootfs/etc/hostname
           - echo "${lxcName}" > /var/lib/lxc/${lxcName}/rootfs/etc/hostname
           #
-          # Create new SSH Host keys
+          # Install OpenSSH
           - lxc-start ${lxcName}
-          - lxc-attach ${lxcName} -- dpkg-reconfigure openssh-server
+          # Wait for network
+          - attempts=50
+          - reachable=0
+          - while [ $reachable -eq 0 ];
+          - do
+          -   sleep 1
+          -   host=`lxc-ls -f -F IPV4 --filter ${lxcName} | grep -v IPV4`
+          -   ping -c1 -w1 $host > /dev/null 2> /dev/null
+          -   if [ "$?" -eq 0 ];
+          -   then
+          -     reachable=1
+          -   else
+          -     echo "Status=$?, IP=$host"
+          -     attempts=`expr $attempts - 1`
+          -     if [ "$attempts" -le 1 ];
+          -     then
+          -       echo "Ping Timeout - LXC start failed"
+          -       lxc-stop ${lxcName}
+          -       echo "update=FAILED" > ${bamboo_build_working_directory}/status.txt
+          -       exit 1
+          -     fi
+          -   fi    
+          - done
+          # Got IP and can ping server - wait another 15 sec
+          - sleep 15
+          # Now install OpenSSH-Server
+          - lxc-attach ${lxcName} -- apt install -y openssh-server
+          # And power it off. Finish building the container
           - lxc-attach ${lxcName} -- poweroff
           #
           - echo "update=DONE" > ${bamboo_build_working_directory}/status.txt
@@ -630,6 +657,28 @@ Topotest_Ubuntu1804_amd64:
           - LXCvm=TEST_${LXCname}
           #
           - ssh ci@${LXChost} "tar xzf share/frr-source.tar.gz"
+
+    # - script:
+    #     interpreter: shell
+    #     scripts:
+    #       - "#!/usr/bin/env bash"
+    #       # For Debugging define the ci_script_verbose variable in config to some value
+    #       - if [ "$bamboo_ci_script_verbose" != "" ]; then
+    #       -     set -x
+    #       - fi
+    #       #
+    #       - if [ "${bamboo.LXC.update}" = "SKIP" ]; then
+    #       -   echo "Skipped. LXC Image was not rebuilt"
+    #       -   exit 0
+    #       - elif [ "${bamboo.LXC.boot}" != "DONE" ]; then
+    #       -   echo "Skipped. LXC Image was not started (start failure)"
+    #       -   exit 0
+    #       - fi
+    #       #
+    #       - . ${bamboo_build_working_directory}/README.SourceVersion.txt
+    #       - LXCname=${lxcTemplate}_${lxcRelease}_${lxcArch}
+    #       # Rename README.SourceVersion.temp to README.SourceVersion.txt to mark working container
+    #       - mv /var/lib/lxc/${LXCname}/rootfs/etc/README.SourceVersion.temp /var/lib/lxc/${LXCname}/rootfs/etc/README.SourceVersion.txt
 
   # final-tasks:
   #    - script:
